### ISSUE TITLE
Laravel10 不支持 

### ISSUE THREAD

**Issue by gyp719** [GodForHeart/laravel-optimizer#1]
Problem 1
    - Root composer.json requires godforheart/laravel-optimizer * -> satisfiable by godforheart/laravel-optimizer[dev-main, v1.0.0, v1.0.1, v1.0.2, 9999999-dev].
    - godforheart/laravel-optimizer[dev-main, v1.0.0, ..., v1.0.2] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require godforheart/laravel-optimizer:*" to figure out if any version is installable, or "composer require godforheart/laravel-optimizer:^2.1" if you know which you need.

**Comment by GodForHeart** [comment]
已支持
