### ISSUE TITLE
当请求一个不存在的uri 地址是， 会抛出异常

### ISSUE THREAD

**Issue by gyp719** [GodForHeart/laravel-optimizer#2]
Error: Call to a member function uri() on null in vendor/godforheart/laravel-optimizer/src/Middleware/OptimizerLog.php:79
Stack trace:

**Comment by GodForHeart** [comment]
已优化

**Comment by gyp719** [comment]
访问一个不存在的地址接口 ，依旧有 错误

Error: Call to a member function uri() on null in /home/vagrant/Code/Tools/vendor/godforheart/laravel-optimizer/src/Middleware/OptimizerLog.php:88
Stack trace:
#0 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Godforheart\LaravelOptimizer\Middleware\OptimizerLog->handle()
#1 /home/vagrant/Code/Tools/app/Http/Middleware/ValidateRequestParamsMiddleware.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#2 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\ValidateRequestParamsMiddleware->handle()
#3 /home/vagrant/Code/Tools/app/Http/Middleware/TraceRequestId.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#4 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\TraceRequestId->handle()
#5 /home/vagrant/Code/Tools/app/Http/Middleware/BanRefererMiddleware.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#6 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\BanRefererMiddleware->handle()
#7 /home/vagrant/Code/Tools/app/Http/Middleware/BanIPMiddleware.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#8 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\BanIPMiddleware->handle()
#9 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#10 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#11 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#12 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#13 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#14 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#15 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#16 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#17 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#19 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\HandleCors->handle()
#21 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\Http\Middleware\TrustProxies->handle()
#23 /home/vagrant/Code/Tools/app/Http/Middleware/AcceptHeader.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\Http\Middleware\AcceptHeader->handle()
#25 /home/vagrant/Code/Tools/vendor/keepsuit/laravel-opentelemetry/src/Support/HttpServer/TraceRequestMiddleware.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Keepsuit\LaravelOpenTelemetry\Support\HttpServer\TraceRequestMiddleware->handle()
#27 /home/vagrant/Code/Tools/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#28 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#29 /home/vagrant/Code/Tools/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#30 /home/vagrant/Code/Tools/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle()
#31 {main}

**Comment by gyp719** [comment]
7/vendor/godforheart/laravel-optimizer/src/Middleware/OptimizerLog.php:88

<img width="966" alt="image" src="https://github.com/user-attachments/assets/d4a18bcf-9b64-4f46-b60c-c2eb9c1398b8">

**Comment by gyp719** [comment]
@GodForHeart
