### ISSUE TITLE
当出触发了 HEAD 请求， 没有返回任何响应时， 回报错

### ISSUE THREAD

**Issue by gyp719** [GodForHeart/laravel-optimizer#3]
异常是由于尝试将一个空的 JSON 文本插入到 optimizer_logs 表的 response_content 列中引起的。在插入数据时，JSON 文本应该是有效的，但在这种情况下，文档是空的，导致了异常。

{
	"traceId": "04cba59863054e1647f98c08b6fd6346",
	"exception": "Illuminate\\Database\\QueryException",
	"message": "SQLSTATE[22032]: <<Unknown error>>: 3140 Invalid JSON text: \"The document is empty.\" at position 0 in value for column 'optimizer_logs.response_content'. (Connection: mysql, SQL: insert into `optimizer_logs` (`request_id`, `api_uri`, `method`, `millisecond`, `business_millisecond`, `execution_sql`, `sql_count`, `request_params`, `request_params_length`, `response_content`, `response_content_length`, `created_at`, `updated_at`) values (06e1279e-f90c-4786-84d6-df4b82c8428e, /, HEAD, 95.251083374023, 26.411056518555, [{\"sql\":\"insert into `http_logs` (`name`, `method`, `scheme`, `host`, `port`, `path`, `query`, `payload`, `headers`, `ip`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\",\"bindings\":[\"generated::RNvCqO3T5YPF1k76\",\"HEAD\",\"https\",\"xxx.com\",443,\"\\/\",\"[]\",\"[]\",\"{\\\"connection\\\":[\\\"keep-alive\\\"],\\\"accept-encoding\\\":[\\\"gzip, deflate, br\\\"],\\\"postman-token\\\":[\\\"d443fe0e-91b9-4bd2-906b-de29cc2bf8c9\\\"],\\\"cache-control\\\":[\\\"no-cache\\\"],\\\"accept\\\":[\\\"*\\\\\\/*\\\"],\\\"host\\\":[\\\"tools.mgtv100.com\\\"],\\\"user-agent\\\":[\\\"spatie\\\\\\/laravel-uptime-monitor uptime checker\\\"]}\",\"27.17.112.145\",\"2024-09-23 14:27:46\",\"2024-09-23 14:27:46\"],\"time\":0.01549,\"connection\":\"mysql\"}], 1, [], 2, , 0, 2024-09-23 14:27:46, 2024-09-23 14:27:46))"
}

**Comment by GodForHeart** [comment]
问题已修复
