### ISSUE TITLE
这个错误 可以优化下吗？

### ISSUE THREAD

**Issue by gyp719** [GodForHeart/laravel-optimizer#4]
`[2024-11-14 16:28:07] production.ERROR: OptimizerPersistJob: {"traceId":"ca04da13ffed20d2b114a10923b5abb7","exception":"Illuminate\\Database\\QueryException","message":"SQLSTATE[22032]: <<Unknown error>>: 3140 Invalid JSON text: \"Invalid value.\" at position 0 in value for column 'optimizer_logs.response_content'. (Connection: mysql, SQL: insert into `optimizer_logs` (`request_id`, `api_uri`, `method`, `millisecond`, `business_millisecond`, `execution_sql`, `sql_count`, `request_params`, `request_params_length`, `response_content`, `response_content_length`, `created_at`, `updated_at`) values (6f8ad481-b606-4315-a17c-9f296fc53a5b, telescope/{view?}, GET, 15.293121337891, 15.294075012207, [{\"sql\":\"insert into `http_logs` (`name`, `method`, `scheme`, `host`, `port`, `path`, `query`, `payload`, `headers`, `ip`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)\",\"bindings\":[\"telescope\",\"GET\",\"https\",\"tools.mgtv100.com\",443,\"telescope\",\"[]\",\"[]\",\"{\\\"user-agent\\\":[\\\"Mozilla\\\\\\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\\\\\\/537.36 (KHTML, like Gecko) Chrome\\\\\\/130.0.0.0 Safari\\\\\\/537.36\\\"],\\\"accept-language\\\":[\\\"zh-CN,zh;q=0.9,en;q=0.8,ar;q=0.7\\\"],\\\"scheme\\\":[\\\"https\\\"],\\\"sec-ch-ua\\\":[\\\"\\\\\\\"Chromium\\\\\\\";v=\\\\\\\"130\\\\\\\", \\\\\\\"Google Chrome\\\\\\\";v=\\\\\\\"130\\\\\\\", \\\\\\\"Not?A_Brand\\\\\\\";v=\\\\\\\"99\\\\\\\"\\\"],\\\"accept-encoding\\\":[\\\"gzip, deflate, br, zstd\\\"],\\\"sec-purpose\\\":[\\\"prefetch;prerender\\\"],\\\"sec-fetch-mode\\\":[\\\"navigate\\\"],\\\"remote-addr\\\":[\\\"27.16.227.1\\\"],\\\"connection\\\":[\\\"close\\\"],\\\"sec-fetch-site\\\":[\\\"none\\\"],\\\"sec-ch-ua-platform\\\":[\\\"\\\\\\\"macOS\\\\\\\"\\\"],\\\"sec-ch-ua-mobile\\\":[\\\"?0\\\"],\\\"server-port\\\":[443],\\\"sec-fetch-user\\\":[\\\"?1\\\"],\\\"cookie\\\":[\\\"view=eyJpdiI6IlJYS1hxaFhCTUxwWkh5MkpRUnpMU3c9PSIsInZhbHVlIjoiQkxneU5DbU41Yk5zVmttNVd1bUJEWXlycUV3bjYvR2ZHQUMvYk5xb1cvMWxWVEVJR1VaWjVyWXVVN01YTldpKyIsIm1hYyI6ImY5NGFjZTFkYzFhYWYyMWZkMzg3YzFkYjA0OTI3MDgxOGNjODc1ZjVkYTExMmM1ZTE0OGE3MGZlYzIzYmM4OWMiLCJ0YWciOiIifQ%3D%3D; Hm_lvt_3df73d8f6754d355e91c9597c9763ab6=1731051976; HMACCOUNT=203901AF582922B6; Hm_lpvt_3df73d8f6754d355e91c9597c9763ab6=1731052002; _session=eyJpdiI6IkhxYXJRRDlrMFk5aVUxajVma2Jhc1E9PSIsInZhbHVlIjoialpYVFM1ODluRHltR3JWSnZteVo4R1JPUXllWnM4U2t6WnRHWXNKWi9wWFcxYUFPaUVpWU1qMTQ4Y1hIckpVZlNZT0twd0xRaGlBUm9UZGJrT3JaemNQS01RS0ZMQVRCZkhTQWJzVFU0b0J5VEtac0Q5K3Zrd0hPYnhBWGdDRnoiLCJtYWMiOiI3NjM0ZTFiZmMyMjY0YTMwNTNmMGU5Y2UxMWNiMTY4NmY2NmUzMTE3NjhlYTdiNTQ3MDYxMDljNmUxOTBkNDgwIiwidGFnIjoiIn0%3D\\\"],\\\"upgrade-insecure-requests\\\":[1],\\\"sec-fetch-dest\\\":[\\\"document\\\"],\\\"x-forwarded-for\\\":[\\\"27.16.227.1\\\"],\\\"accept\\\":[\\\"text\\\\\\/html,application\\\\\\/xhtml+xml,application\\\\\\/xml;q=0.9,image\\\\\\/avif,image\\\\\\/webp,image\\\\\\/apng,*\\\\\\/*;q=0.8,application\\\\\\/signed-exchange;v=b3;q=0.7\\\"],\\\"purpose\\\":[\\\"prefetch\\\"],\\\"host\\\":[\\\"tools.mgtv100.com\\\"]}\",\"27.16.227.1\",\"2024-11-14 16:28:07\",\"2024-11-14 16:28:07\"],\"time\":0.00846,\"connection\":\"mysql\"}], 1, [], 2, <!DOCTYPE html>`

**Comment by GodForHeart** [comment]
已优化，非常规json输出兼容上
